[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
ffi = true  # not very safe to have on
fs_permissions = [{ access = "read", path = "./broadcast" }]
# MORE HERE: https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
